{
 "title": "App + OTEL Telemetry",
 "tags": [
  "otel",
  "fastapi",
  "prometheus",
  "jaeger"
 ],
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Spans Exported per Minute",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 6 },
   "targets": [
    {
     "expr": "rate(otelcol_exporter_sent_spans_total[1m])*60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OTEL Collector CPU Usage",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 6 },
   "targets": [
    {
     "expr": "rate(otelcol_process_cpu_seconds_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Can Access document:123",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 6 },
   "targets": [
    {
     "expr": "can_access{relation=\"can_access\", object=\"document:123\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Access Checks per Minute",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 8, "h": 6 },
   "targets": [
    {
     "expr": "sum(rate(check_access_calls_total[1m])) by(instance) * 60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Access Checks Passed per Minute",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 6, "w": 8, "h": 6 },
   "targets": [
    {
     "expr": "sum(rate(check_access_calls_total{allowed=\"True\"}[1m])) by(user) * 60",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Access Checks Denied per Minute",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 6, "w": 8, "h": 6 },
   "targets": [
    {
     "expr": "sum(rate(check_access_calls_total{allowed=\"False\"}[1m])) by(user) * 60",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Up Status",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 24, "h": 6 },
   "targets": [
    { "expr": "up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Recent Traces",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "service": "openfga-python-client" }
   ]
  }
 ]
}