apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: otel-fga
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: "0.0.0.0:4318"
    exporters:
      prometheus:
        endpoint: "0.0.0.0:9090"
      debug:
        verbosity: detailed
    processors:
      batch:
    service:
      telemetry:
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: '0.0.0.0'
                    port: 8888
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]