version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - otel-collector
      - openfga
    volumes:
      - ./ids:/tmp/ids
    restart: on-failure

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"
      - "9090:9090"
      - "8888:8888"
    depends_on:
      - jaeger
    restart: on-failure

  jaeger:
    image: jaegertracing/all-in-one:1.54
    ports:
      - "16686:16686"
      - "14250:14250"
    environment:
      COLLECTOR_OTLP_ENABLED: true

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-conf/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-conf/provisioning:/etc/grafana/provisioning
      - ./grafana-conf/dashboards:/etc/grafana/dashboards

  openfga:
    image: openfga/openfga:latest
    ports:
      - "8080:8080"
    command: run

  init-openfga:
    image: curlimages/curl:latest
    volumes:
      - ./openfga_model.json:/openfga_model.json
      - ./init_openfga.sh:/init_openfga.sh
      - ./ids:/tmp/ids
    entrypoint: ["/bin/sh", "/init_openfga.sh"]
    depends_on:
      - openfga
