global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'otel-collector-internal'
    static_configs:
      - targets: ['otel-collector:8888']

  - job_name: 'otel-collector-app-metrics'
    static_configs:
      - targets: ['otel-collector:9090']