apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: otel-fga
spec:
  selector:
    app: jaeger
  ports:
    - name: query
      port: 16686
      targetPort: 16686
    - name: otlp-grpc
      port: 14250
      targetPort: 14250
    - name: otlp-http
      port: 4318
      targetPort: 4318
  type: ClusterIP