apiVersion: v1
kind: Service
metadata:
  name: jaeger-ui
  namespace: otel-fga
spec:
  type: NodePort
  selector:
    app: jaeger
  ports:
    - port: 16686
      targetPort: 16686
      nodePort: 30004