apiVersion: apps/v1
kind: Deployment
metadata:
  name: openfga
  namespace: otel-fga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openfga
  template:
    metadata:
      labels:
        app: openfga
    spec:
      containers:
      - name: openfga
        image: openfga/openfga:latest
        args:
        - run
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
      volumes:
      - name: openfga-model
        configMap:
          name: openfga-config
      - name: init-script
        configMap:
          name: openfga-config