apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: otel-fga
spec:
  selector:
    app: otel-collector
  ports:
  - name: otlp-http
    port: 4318
    targetPort: 4318
  - name: prometheus
    port: 9090
    targetPort: 9090
  - name: metrics
    port: 8888
    targetPort: 8888
  type: ClusterIP